defmodule CrucibleTrace do
  @moduledoc """
  CausalTrace - Structured causal reasoning chain logging for LLM code generation.

  This library provides tools for capturing, analyzing, and visualizing the
  decision-making process of LLMs during code generation. It enables transparency
  and debugging by logging causal reasoning chains with events, alternatives,
  and confidence levels.

  ## Quick Start

      # Parse LLM output containing event tags
      {:ok, chain} = CrucibleTrace.parse_llm_output(llm_response, "My Task")

      # Create events manually
      event = CrucibleTrace.create_event(
        :hypothesis_formed,
        "Use GenServer for state management",
        "Need concurrent access and fault tolerance",
        alternatives: ["ETS table", "Agent"],
        confidence: 0.85
      )

      # Add to a chain
      chain = CrucibleTrace.new_chain("API Implementation")
      chain = CrucibleTrace.add_event(chain, event)

      # Save and visualize
      CrucibleTrace.save(chain)
      CrucibleTrace.visualize(chain)

  ## Main Features

  - **Event Tracking**: Capture decision points with alternatives and reasoning
  - **Chain Management**: Organize events into coherent reasoning chains
  - **LLM Parsing**: Extract events from LLM output automatically
  - **Storage**: Persist chains to disk in JSON format
  - **Visualization**: Generate interactive HTML views of reasoning chains
  - **Analysis**: Query and filter events, calculate statistics
  """

  alias CrucibleTrace.{Chain, Event, Parser, Storage, Viewer}

  # Chain Operations

  @doc """
  Creates a new empty chain.

  ## Examples

      iex> chain = CrucibleTrace.new_chain("User Authentication")
      iex> chain.name
      "User Authentication"
  """
  defdelegate new_chain(name, opts \\ []), to: Chain, as: :new

  @doc """
  Adds an event to a chain.
  """
  defdelegate add_event(chain, event), to: Chain

  @doc """
  Adds multiple events to a chain.
  """
  defdelegate add_events(chain, events), to: Chain

  # Event Operations

  @doc """
  Creates a new event.

  ## Parameters

  - `type` - Event type atom (see `CrucibleTrace.Event` for types)
  - `decision` - What was decided
  - `reasoning` - Why this decision was made
  - `opts` - Optional fields:
    - `:alternatives` - List of alternatives considered
    - `:confidence` - Confidence level (0.0-1.0)
    - `:code_section` - Related code section
    - `:spec_reference` - Related specification reference
    - `:metadata` - Additional metadata map

  ## Examples

      iex> event = CrucibleTrace.create_event(
      ...>   :pattern_applied,
      ...>   "Use Supervisor for fault tolerance",
      ...>   "Application needs to recover from crashes",
      ...>   alternatives: ["Manual restart", "No supervision"],
      ...>   confidence: 0.95
      ...> )
      iex> event.type
      :pattern_applied
  """
  defdelegate create_event(type, decision, reasoning, opts \\ []), to: Event, as: :new

  @doc """
  Validates an event.

  Returns `{:ok, event}` if valid, `{:error, reason}` otherwise.
  """
  defdelegate validate_event(event), to: Event, as: :validate

  # Parsing Operations

  @doc """
  Parses LLM output to extract causal trace events.

  The LLM output should contain XML-style event tags as generated by
  prompts from `build_causal_prompt/1`.

  Returns `{:ok, chain}` if successful, `{:error, reason}` otherwise.

  ## Examples

      See tests and documentation for usage examples.
  """
  def parse_llm_output(text, chain_name, opts \\ []) do
    Parser.parse_to_chain(text, chain_name, opts)
  end

  @doc """
  Parses LLM output and returns just the events.

  Returns `{:ok, events}` if successful, `{:error, reason}` otherwise.
  """
  defdelegate parse_events(text), to: Parser, as: :parse

  @doc """
  Extracts just the code from LLM output, removing event tags.

  Useful for getting clean code after parsing events.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate extract_code(text), to: Parser

  @doc """
  Builds a prompt that instructs the LLM to emit causal trace events.

  Takes your base specification and wraps it with event emission instructions.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate build_causal_prompt(base_spec), to: Parser

  @doc """
  Validates that text contains properly formatted events.

  Returns `{:ok, count}` or `{:error, issues}`.
  """
  defdelegate validate_events(text), to: Parser

  # Storage Operations

  @doc """
  Saves a chain to disk.

  ## Options

  - `:storage_dir` - Directory to store chains (default: "causal_traces")
  - `:format` - Storage format, currently only `:json` (default: :json)

  Returns `{:ok, file_path}` if successful, `{:error, reason}` otherwise.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate save(chain, opts \\ []), to: Storage

  @doc """
  Loads a chain from disk by ID.

  Returns `{:ok, chain}` if found, `{:error, reason}` otherwise.
  """
  defdelegate load(chain_id, opts \\ []), to: Storage

  @doc """
  Lists all saved chains.

  Returns `{:ok, chain_list}` with metadata for each chain.
  """
  defdelegate list_chains(opts \\ []), to: Storage, as: :list

  @doc """
  Deletes a chain from disk.

  Returns `:ok` if successful, `{:error, reason}` otherwise.
  """
  defdelegate delete(chain_id, opts \\ []), to: Storage

  @doc """
  Searches for chains matching criteria.

  ## Options

  - `:name_contains` - Filter by name substring
  - `:created_after` - Filter by creation date
  - `:created_before` - Filter by creation date
  - `:min_events` - Minimum number of events
  - `:max_events` - Maximum number of events

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate search(query, opts \\ []), to: Storage

  @doc """
  Exports a chain to a different format.

  Supported formats: `:json`, `:markdown`, `:csv`

  Returns `{:ok, content}` if successful, `{:error, reason}` otherwise.
  """
  defdelegate export(chain, format, opts \\ []), to: Storage

  # Visualization Operations

  @doc """
  Generates an HTML visualization of a chain.

  ## Options

  - `:title` - Page title (default: chain name)
  - `:style` - CSS theme, `:light` or `:dark` (default: :light)
  - `:include_statistics` - Show statistics panel (default: true)
  - `:include_timeline` - Show timeline visualization (default: true)

  Returns the HTML content as a string.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate visualize(chain, opts \\ []), to: Viewer, as: :generate_html

  @doc """
  Saves an HTML visualization to a file.

  Returns `{:ok, file_path}` if successful, `{:error, reason}` otherwise.
  """
  defdelegate save_visualization(chain, file_path, opts \\ []), to: Viewer, as: :save_html

  @doc """
  Opens the chain visualization in the default browser.

  Creates a temporary HTML file and opens it.

  Returns `{:ok, temp_file_path}` if successful, `{:error, reason}` otherwise.
  """
  defdelegate open_visualization(chain, opts \\ []), to: Viewer, as: :open_in_browser

  # Analysis Operations

  @doc """
  Gets statistics about a chain.

  Returns a map with:
  - `total_events` - Total number of events
  - `event_type_counts` - Count per event type
  - `avg_confidence` - Average confidence across all events
  - `duration_seconds` - Time from first to last event

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate statistics(chain), to: Chain

  @doc """
  Finds decision points where alternatives were rejected.

  Returns a list of decision events with their alternatives.
  """
  defdelegate find_decision_points(chain), to: Chain

  @doc """
  Finds events with low confidence (below threshold).

  Default threshold is 0.7.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate find_low_confidence(chain, threshold \\ 0.7), to: Chain

  @doc """
  Gets events of a specific type from the chain.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate get_events_by_type(chain, type), to: Chain

  @doc """
  Filters events in a chain based on a predicate function.

  ## Examples

      See tests and documentation for usage examples.
  """
  defdelegate filter_events(chain, predicate_fn), to: Chain

  @doc """
  Sorts events in a chain by timestamp.

  Order can be `:asc` or `:desc`.
  """
  defdelegate sort_by_timestamp(chain, order \\ :asc), to: Chain

  @doc """
  Merges two chains together, combining their events.
  """
  defdelegate merge_chains(chain1, chain2), to: Chain, as: :merge

  # Conversion Operations

  @doc """
  Converts a chain to a map suitable for JSON encoding.
  """
  defdelegate chain_to_map(chain), to: Chain, as: :to_map

  @doc """
  Creates a chain from a map (e.g., from JSON parsing).
  """
  defdelegate chain_from_map(map), to: Chain, as: :from_map

  @doc """
  Converts an event to a map suitable for JSON encoding.
  """
  defdelegate event_to_map(event), to: Event, as: :to_map

  @doc """
  Creates an event from a map (e.g., from JSON parsing).
  """
  defdelegate event_from_map(map), to: Event, as: :from_map
end
